// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5yr_dP9rwbociwevLHgIgRa029BxYDE',
    appId: '1:576847968556:web:6ec6debee2154bd116d489',
    messagingSenderId: '576847968556',
    projectId: 'lawma-project',
    authDomain: 'lawma-project.firebaseapp.com',
    storageBucket: 'lawma-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8iZ3IRT-OCLZCZDPOtu0DF8NALRuZgcM',
    appId: '1:576847968556:android:66dba750d0135b4e16d489',
    messagingSenderId: '576847968556',
    projectId: 'lawma-project',
    storageBucket: 'lawma-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc0q6P9VJ99vazrUqfDMc1QLGPAgdzgWQ',
    appId: '1:576847968556:ios:48a16faa4354987c16d489',
    messagingSenderId: '576847968556',
    projectId: 'lawma-project',
    storageBucket: 'lawma-project.appspot.com',
    iosClientId:
        '576847968556-0eosd881lv8aivsc5uf23gbgm3kspre2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawmaApp',
  );
}
